model_name: 'ResNet34'
optim: 'SGD'

# Hyper params used for transfer learning training
LR: 0.01
batch_size: 64
epochs: 150
momentum: 0.9

# used ONLY for baseline training
baseline_LR: 0.01
baseline_batch_size: 64
baseline_epochs: 100
